### ISSUE TITLE
KeyError: 'keys'

### ISSUE THREAD

**Issue by VladVKozlov** [anijackich/kinescope-dl#17]
I'm trying to download this video for my personal usage, but I get this error:
PS D:\Gleb Kornilov Crypto videos> ./kinescope-dl.exe --best-quality -r https://id.glebkornilov.ru/ https://kinescope.io/c7db6f3b-d54f-4ed4-bad1-3cebf1726b4c output.mp4
= OPTIONS ============================
[*] 1080p is selected
======================================

= DOWNLOADING =================
Traceback (most recent call last):
  File "kinescope-dl.py", line 73, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "kinescope-dl.py", line 64, in main
  File "kinescope\downloader.py", line 144, in download
  File "kinescope\downloader.py", line 70, in _get_license_key
KeyError: 'keys'
[44676] Failed to execute script 'kinescope-dl' due to unhandled exception!

We need some explanation on this and how to fix

**Comment by anijackich** [comment]
Dublicate of https://github.com/anijackich/kinescope-dl/issues/11
