### ISSUE TITLE
downloader.py line 144 KeyError

### ISSUE THREAD

**Issue by soy789** [anijackich/kinescope-dl#25]
Hello.
Windows version
A month ago, everything was working smoothly, but now we're encountering an error. Could you please help us resolve it?

= OPTIONS ============================
[*] 720p is selected
======================================

= DOWNLOADING =================
Traceback (most recent call last):
  File "kinescope-dl.py", line 73, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "kinescope-dl.py", line 64, in main
  File "kinescope\downloader.py", line 144, in download
  File "kinescope\downloader.py", line 70, in _get_license_key
KeyError: 'keys'
[5624] Failed to execute script 'kinescope-dl' due to unhandled exception!

**Comment by soy789** [comment]
https://github.com/anijackich/kinescope-dl/issues/11
