### ISSUE TITLE
Error format URL shema

### ISSUE THREAD

**Issue by santerr80** [anijackich/kinescope-dl#28]
PS D:\Python\sf-downloader> kinescope-dl -r https://lms.skillfactory.ru/ --best-quality https://kinescope.io/embed/uyWMhQwGjCH8JBiQ7etKku?externalid=5795 video.mp4
= OPTIONS ============================
[*] 1080p is selected
======================================

= DOWNLOADING =================
Video:   0%|          | [0/5]
Traceback (most recent call last):
  File "kinescope-dl.py", line 73, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "kinescope-dl.py", line 64, in main
  File "kinescope\downloader.py", line 146, in download
  File "kinescope\downloader.py", line 113, in _fetch_segments
  File "kinescope\downloader.py", line 94, in _fetch_segment
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 575, in request
  File "requests\sessions.py", line 486, in prepare_request
  File "requests\models.py", line 368, in prepare
  File "requests\models.py", line 439, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '0/78644115/1080p.mp4?kcd=AAAAAABAr0A': No scheme supplied. Perhaps you meant https://0/78644115/1080p.mp4?kcd=AAAAAABAr0A?
[2344] Failed to execute script 'kinescope-dl' due to unhandled exception!

**Comment by SlavaVasilyevQA** [comment]
такая же проблема:

```bash
kinescope-dl https://kinescope.io/18403498-a144-4d5a-8eb2-7ea333895ad6 output.mp4

= OPTIONS ============================
1) 360p   2) 480p   3) 720p   4) 1080p
> Quality: 4
[*] 1080p is selected
======================================

= DOWNLOADING =================
Video:   0%|          | [0/7]
Traceback (most recent call last):
  File "kinescope-dl.py", line 73, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "kinescope-dl.py", line 64, in main
  File "kinescope\downloader.py", line 146, in download
  File "kinescope\downloader.py", line 113, in _fetch_segments
  File "kinescope\downloader.py", line 94, in _fetch_segment
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 575, in request
  File "requests\sessions.py", line 486, in prepare_request
  File "requests\models.py", line 368, in prepare
  File "requests\models.py", line 439, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '0/80686858/1080p.mp4?kcd=AAAAAABAr0A': No scheme supplied. Perhaps you meant https://0/80686858/1080p.mp4?kcd=AAAAAABAr0A?
[17892] Failed to execute script 'kinescope-dl' due to unhandled exception!
```
@anijackich нужна ваша помощь 🙏🙏🙏

**Comment by nvv-vlad** [comment]
Same problem

```

= OPTIONS ============================
1) 360p   2) 480p   3) 720p   4) 1080p
> Quality: 3
[*] 720p is selected
======================================

= DOWNLOADING =================
Video:   0%|          | [0/7]
Traceback (most recent call last):
  File "kinescope-dl.py", line 73, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "kinescope-dl.py", line 64, in main
  File "kinescope\downloader.py", line 146, in download
  File "kinescope\downloader.py", line 113, in _fetch_segments
  File "kinescope\downloader.py", line 94, in _fetch_segment
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 575, in request
  File "requests\sessions.py", line 486, in prepare_request
  File "requests\models.py", line 368, in prepare
  File "requests\models.py", line 439, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '0/78671076/720p.mp4?kcd=AAAAAABAr0A': No scheme supplied. Perhaps you meant https://0/78671076/720p.mp4?kcd=AAAAAABAr0A?
[25852] Failed to execute script 'kinescope-dl' due to unhandled exception!
```

@anijackich all hope is on you

**Comment by ilyagp** [comment]
I had the same issue today and managed to download 10 videos using PR #27. Is this wonderful fix already mature enough to be merged into master?
