### ISSUE TITLE
Not working with new master.m3u8 videos

### ISSUE THREAD

**Issue by delfer** [anijackich/kinescope-dl#30]
In web console I see: https://kinescope.io/new-manifest/ff2d3677-9c58-4f64-ac39-37b9b7e3b244/master.m3u8?duration=3338&expires=1733390603&seek=6214&token=

In kinescope-dl (built form commit 8afc48792439f83fe59c77e46748a95fbcca81c3)

```
dist/kinescope-dl -r https://conf.ontico.ru/ https://kinescope.io/embed/0ch7azdw6t5pZX9zCCtufh tbank-videocall-arch.mp4

Traceback (most recent call last):
  File "kinescope-dl.py", line 79, in <module>
    main()
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "kinescope-dl.py", line 58, in main
    downloader: KinescopeDownloader = KinescopeDownloader(kinescope_video, temp, ffmpeg_path=ffmpeg_path, mp4decrypt_path=mp4decrypt_path)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "kinescope/downloader.py", line 40, in __init__
    self.mpd_master: MPEGDASH = self._fetch_mpd_master()
                                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "kinescope/downloader.py", line 136, in _fetch_mpd_master
    return MPEGDASHParser.parse(self.http.get(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mpegdash/parser.py", line 30, in parse
  File "mpegdash/parser.py", line 26, in load_xmldom
  File "xml/dom/minidom.py", line 2000, in parseString
  File "xml/dom/expatbuilder.py", line 922, in parseString
  File "xml/dom/expatbuilder.py", line 220, in parseString
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 3755992
[PYI-31156:ERROR] Failed to execute script 'kinescope-dl' due to unhandled exception!
```

**Comment by Di9** [comment]
Have you tried https://github.com/anijackich/kinescope-dl/pull/27 this fixing problem with new manifest
(checkout [manifest-update](https://github.com/akolnoochenko/kinescope-dl/tree/manifest-update) branch and build app again)
