### ISSUE TITLE
Invalid URL '0/78737348/360p.mp4?kcd=AAAAAAA-r0A': No scheme supplied. Perhaps you meant https://0/78737348/360p.mp4?kcd=AAAAAAA-r0A?

### ISSUE THREAD

**Issue by minzak** [anijackich/kinescope-dl#32]
Im use Debian12 with latest binary file (kinescope-dl)

I got a simple error with relative/full path.

Its can helps:
[master.mpd.gz](https://github.com/user-attachments/files/18281466/master.mpd.gz)
[clearkey.json](https://github.com/user-attachments/files/18281469/clearkey.json)

```
me@z230 /work $ ./kinescope-dl https://kinescope.io/7xCwa7bnDACkMzDH1Mt1ww video.mp4
= OPTIONS ============================
1) 360p   2) 480p   3) 720p   4) 1080p
> Quality: 1
[*] 360p is selected
======================================

= DOWNLOADING =================
Video:   0%|          | [0/4]
Traceback (most recent call last):
  File "kinescope-dl.py", line 73, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "kinescope-dl.py", line 64, in main
  File "kinescope/downloader.py", line 146, in download
  File "kinescope/downloader.py", line 113, in _fetch_segments
  File "kinescope/downloader.py", line 94, in _fetch_segment
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 575, in request
  File "requests/sessions.py", line 486, in prepare_request
  File "requests/models.py", line 368, in prepare
  File "requests/models.py", line 439, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '0/78737348/360p.mp4?kcd=AAAAAAA-r0A': No scheme supplied. Perhaps you meant https://0/78737348/360p.mp4?kcd=AAAAAAA-r0A?
[4632] Failed to execute script 'kinescope-dl' due to unhandled exception!
```

**Comment by emerysleeper** [comment]
Same. I'm using windows 10, tried adding -r https://kinescope.io and tried adding --best_quality. Still to no avail, the error is exactly the same.

**Comment by Gricefer** [comment]
kinescope-dl -r https://nechto1.ru/ https://kinescope.io/embed/tfzYhauubVdUcduP7wTRk9 video_1.mp4
= OPTIONS ============================
1) 360p   2) 480p   3) 720p
> Quality: 3
[*] 720p is selected
======================================

= DOWNLOADING =================
Video:   0%|          | [0/26]
Traceback (most recent call last):
  File "kinescope-dl.py", line 73, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "kinescope-dl.py", line 64, in main
  File "kinescope/downloader.py", line 146, in download
  File "kinescope/downloader.py", line 113, in _fetch_segments
  File "kinescope/downloader.py", line 94, in _fetch_segment
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 575, in request
  File "requests/sessions.py", line 486, in prepare_request
  File "requests/models.py", line 368, in prepare
  File "requests/models.py", line 439, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '0/78689917/720p.mp4?kcd=AAAAAABAr0A': No scheme supplied. Perhaps you meant https://0/78689917/720p.mp4?kcd=AAAAAABAr0A?
[79592] Failed to execute script 'kinescope-dl' due to unhandled exception!

**Comment by casualuser** [comment]
It looks like same issue here. Fresh compiled from master branch on macos.

```
(kinescope) ➜  kinescope-dl git:(master) kinescope-dl https://kinescope.io/eJvNX1ga51zCPR3iKk8XWq ./BVP1.mp4
= OPTIONS ============================
1) 360p   2) 480p   3) 720p   4) 1080p
> Quality: 1
[*] 360p is selected
======================================

= DOWNLOADING =================
Video:   0%|          | [0/7]
Traceback (most recent call last):
  File "kinescope-dl.py", line 79, in <module>
    main()
  File "click/core.py", line 1161, in __call__
  File "click/core.py", line 1082, in main
  File "click/core.py", line 1443, in invoke
  File "click/core.py", line 788, in invoke
  File "kinescope-dl.py", line 70, in main
    downloader.download(
  File "kinescope/downloader.py", line 152, in download
    self._fetch_segments(
  File "kinescope/downloader.py", line 119, in _fetch_segments
    self._fetch_segment(segment_url, f)
  File "kinescope/downloader.py", line 100, in _fetch_segment
    BytesIO(self.http.get(segment_url, stream=True).content),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "requests/sessions.py", line 602, in get
  File "requests/sessions.py", line 575, in request
  File "requests/sessions.py", line 486, in prepare_request
  File "requests/models.py", line 368, in prepare
  File "requests/models.py", line 439, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '0/78727286/360p.mp4?kcd=AAAAAABAr0A': No scheme supplied. Perhaps you meant https://0/78727286/360p.mp4?kcd=AAAAAABAr0A?
[PYI-12489:ERROR] Failed to execute script 'kinescope-dl' due to unhandled exception!
Usage: kinescope-dl [OPTIONS] INPUT_URL OUTPUT_FILE
Try 'kinescope-dl --help' for help.

Error: No such option: -B
```

**Comment by casualuser** [comment]
For everyone who met the same issue - this PR fixes the problem https://github.com/anijackich/kinescope-dl/pull/27/files

So to get everything working the PR should be merged to close this issue.

**Comment by Kelbern** [comment]
Can somebody compile the fixed version for Windows x64 ? I get errors for missing python modules even after installing it.

**Comment by Kelbern** [comment]
I'm not sure if it's the same by the way. Is it the same issue ? 

C:\kinescop>kinescope-dl -r https://lk.result-university.com/ https://kinescope.io/c37b5fc9-2913-4a1b-99ca-c46e6d780dcf output.mp4
= OPTIONS ============================
1) 360p   2) 480p   3) 720p
> Quality: 3
[*] 720p is selected
======================================

= DOWNLOADING =================
Video:   0%|          | [0/2]
Traceback (most recent call last):
  File "kinescope-dl.py", line 73, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "kinescope-dl.py", line 64, in main
  File "kinescope\downloader.py", line 146, in download
  File "kinescope\downloader.py", line 113, in _fetch_segments
  File "kinescope\downloader.py", line 94, in _fetch_segment
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 575, in request
  File "requests\sessions.py", line 486, in prepare_request
  File "requests\models.py", line 368, in prepare
  File "requests\models.py", line 439, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '?kcd=AAAAAABAr0A': No scheme supplied. Perhaps you meant https://?kcd=AAAAAABAr0A?
[20476] Failed to execute script 'kinescope-dl' due to unhandled exception!

**Comment by d-korolkov** [comment]
Not an engineer.  Got the same errors, but figure out how to make it work. 
1. Download kinescope-dl-master
2. put mp4encrypt.exe inside
3.install all needed modules (pip install **mpegdash** ) / **tqdm** / **requests** 
4. check downloader.py line 23 , put proper ffmpeg_path 
5. use proper command like this 

C:\kinescope-dl-master>python kinescope-dl.py -r "https://hosted-service.com/" --best-quality --ffmpeg-path "C:\ffmpeg\bin\ffmpeg.exe" "https://kinescope.io/embed/blablabla" "video1.mp4"
